<h2 class="mb-5">Chronik aus dem Jahr 2013</h2>

<p>Am&nbsp;<strong>23. Januar 2013</strong>&nbsp;wurde die neue Homepage online gestellt.</p>
<p>Die Sportlerehrung in der Stadthalle Rottweil fand am&nbsp;<strong>15.03.2013&nbsp;</strong>statt, es wurde vom Fanfarenzug geehrt:</p><ul> 	<li>Abele Georg 5. Platz Deutschen Meisterschaften im Fahnenschwingen,</li> 	<li>Ute Günthner 3. Platz im Gruppensynchron bei der Deutschen Meisterschaft im Fahnenschwingen,&nbsp;</li> 	<li>Lorena Karbstein 3. Platz im Gruppensynchron bei der Deutschen Meisterschaft im Fahnenschwingen,&nbsp;</li> 	<li>Melissa Karbstein 3. Platz im Gruppensynchron bei der Deutschen Meisterschaft im Fahnenschwingen,&nbsp;</li> 	<li>Tatjana Ohnmacht 3. Platz im Gruppensynchron bei der Deutschen Meisterschaft im Fahnenschwingen,&nbsp;</li> 	<li>Jessica Vogt 3. Platz im Gruppensynchron bei der Deutschen Meisterschaft im Fahnenschwingen,&nbsp;</li> 	<li>Jessica Vogt 4. Platz ( Damen offene Klasse ) bei den Weltmeisterschaften im Fahnenhochwerfen,&nbsp;</li> 	<li>Jessica Vogt 1. Platz Wettkampfgemeinschaft Konstanz/ Rottweil bei den Weltmeisterschaften im Fahnenhochwerfen.</li> </ul><p>Die Mitgliederversammlung wurde am&nbsp;<strong>17.03.2013</strong>&nbsp;im Gaststätte Liederhalle abgehalten.</p>
<p>Gewählt wurde der Vorsitzender und Musikalischer Leiter Klaus Günthner,</p>
<p>die Kassiererin Ute Günthner und&nbsp;1. Beirat Walter Wiedemann.</p>
<p>Neu gewählt&nbsp; wurde&nbsp;Pressewart Tatjana Ohnmacht und&nbsp;Beisitzer Fahnenschwinger Monika Günthner.</p>
<p>Ehrungen Fanfarenzug</p>
<p><strong>Bronze</strong></p><ul> 	<li>Annette Karbstein</li> 	<li>Andre Lengfeld</li> 	<li>Jasmin Kunz</li> </ul><p><strong>Silber</strong></p><ul> 	<li>Julian Flaig</li> 	<li>Tobias Bucher</li> 	<li>Julia Duttenhöfer</li> 	<li>Arthur Duttenhöfer</li> </ul><p><strong>Gold</strong></p><ul> 	<li>Elvira Roland</li> 	<li>Silke Wiedemann</li> 	<li>Holger Schmid</li> </ul><p>Am&nbsp;<strong>01.05.2013&nbsp;</strong>war am Wasserturm ein gelungenes 1. Mai Fest mit vielen Besuchern. Anschließend durften die Zuschauer mit den Fahnen auch mal ausprobieren; so wie das Fahnenhochwerfen das man nur mit Sicherheitsvorkehrungen üben darf. Eine schöne Einlage war das Showschwingen unserer Fahnenschwinger.</p>
<p>Die Fahnenschwinger vom Fanfarenzug Rottweil hatten am&nbsp;<strong>02.06.2013</strong>&nbsp;bei der Hauptübung des Allgemeinen Deutschen Rottweiler – Klub e. V eine Fahnenschwinger – Show. Die Teilnehmer waren Lorena und Melissa Karbstein, Tatjana Ohnmacht sowie auch Jessica Vogt.</p>
<p>Den 1. Auftritt im Schweizer Jahr war am&nbsp;<strong>03.06.2013&nbsp;</strong>zur Eröffnung. Die Fahnenschwinger des Fanfarenzugs Rottweil hatten ihren Auftritt an der Kapellenkirche.</p>
<p>Der 2. Auftritt war am&nbsp;<strong>05.06.2013&nbsp;</strong>beim schönen Wetter mit den Alphornbläsern.</p>
<p>Beim Landestreffen der Spielmanns- und Fanfarenzüge am&nbsp;<strong>09.06.2013</strong>&nbsp;in Blaufelden &nbsp;traten mit der Startnummer 31 der Fanfarenzug Rottweil mit vier Trommlern und fünf Fahnenschwingern auf.&nbsp;&nbsp;</p>
<p>Bei der Hochzeit am&nbsp;<strong>15.06.2013&nbsp;</strong>unseren Kassiererin Ute Thom, spielte der Fanfarenzug unter der Leitung vom Daniel Flaig auf. Die Fahnenschwinger des Verbandes standen Spalier beim Auszug aus der Kirche. Um dann anschließend mit den Brautpaar zusammen die Fahnen zu Schwingen.</p>
<p>Am&nbsp;<strong>29.06.2013&nbsp;</strong>fand in der BayArena in Leverkusen der 150. Geburtstag der Bayer AG statt. Die Fahnenschwinger der Niederburg Konstanz wurden für diesen Event gebucht. Die Fahnenschwingerkollegen aus Konstanz baten befreundete Fahnenschwinger Gruppen um Mithilfe bei diesem Event. Somit durften die Fahnenschwinger des Fanfarenzugs Rottweil ebenfalls daran teilnehmen. Gemeinsam mit Fahnenschwingern aus Konstanz, Rastatt, Bretten, Markdorf Sternfels, Bad Säckingen und aus dem Vogtland ging die Reise nach Leverkusen. Mit sehr viel Training und dem Koordinieren der Einzelnen Gruppen zu einen ganzen Show teil. Um Punkt 17:30 Uhr war es für die 37 Fahnenschwinger soweit und sie lieferten gemeinsam mit den Flying Drummers und zwei Trommlergruppen eine super Show ab. &nbsp;</p>
<p>Nach einjähriger Pause lockte das Hegnebergfest am&nbsp;<strong>06.07.2013</strong>&nbsp;wieder zahlreiche Menschen in den Rottweiler Stadtteil. Dieses Mal hatten die Organisatoren vom Aktionskreis Hegneberg das Motto „ Schweiz „ gewählt. Auch die Bergwelt durfte nicht fehlen und so war auch die Heidi – Filmmusik zu hören. Die Fahnenschwinger des Fanfarenzugs Rottweil in Begleitung der Alphornbläser boten einen weiteren Höhenpunkt des Programmes.</p>
<p>Bei der Hochzeit von Georg Abele am&nbsp;<strong>27.07.2013&nbsp;</strong>standen die Fahnenschwinger Spalier. Anschließend wurde von ihnen ein Fahnenspiel dargeboten.</p>
<p>Über den Ferienzauber fand am&nbsp;<strong>10.08.2013&nbsp;</strong>eine Jungmusiker Werbung statt. Im Musikpavillon der Konrad – Witz – Schule waren 9 Jugendliche unter der Leitung vom Klaus Günthner dabei. Sie machten Musik mit Trommeln und Fanfaren. &nbsp;</p>
<p>Die 9. Landesmeisterschaften in Fahnenschwingen fanden am&nbsp;<strong>30.08. bis 01.09.2013&nbsp;</strong>in Rottweil statt. Von Tauberbischofsheim im Norden bis Konstanz im Süden nahmen Mitglieder der 11 teilnehmenden Vereine teil. Tatjana Ohnmacht von den Rottweiler Fahnenschwingern machte dort den 1. Platz. Bei den Gruppensynchronschwingen belegten 6 Rottweilerinnen den 3. Platz.</p>
<p>Der letzte Auftritt im Schweizer Jahr fand am&nbsp;<strong>20.10.2013&nbsp;</strong>statt. Das Wetter war windig und regnerisch. Dies hinderte die Fahnenschwinger jedoch nicht davon und sie legte eine gelungene Vorstellung hin.</p>

