<h2 class="mb-5">Chronik aus dem Jahr 2016</h2>

<p>Die Mitgliederversammlung wurde am&nbsp;<strong>13.03.2016</strong>&nbsp;im Gasthaus Hochbrücke abgehalten.</p>
<p>Gewählt wurde der</p><ul> 	<li>stellvertretende Vorsitzende Hans- Peter Bucher</li> 	<li>Schriftführer Thomas Wiedemann</li> 	<li>Pressewart Annette Karbstein</li> 	<li>neu 1. Beirat Thomas Roland</li> 	<li>2. Beirat Daniel Enzmann.</li> </ul><p><strong>Ehrungen Fanfarenzug</strong><br> <strong>Silber</strong></p><ul> 	<li>Hans-Peter Bucher</li> </ul><p><strong>Gold</strong></p><ul> 	<li>Rebecca Wiedemann</li> 	<li>Ursula Grundmann</li> 	<li>Corina Korenjak</li> </ul><p><strong>Ehrungen Landesverband der Spielmanns-und Fanfarenzüge</strong><br> <strong>Bronze</strong></p><ul> 	<li>Hans-Peter Bucher</li> </ul><p>Die Sportlerehrungen in der Stadthalle Rottweil fand am&nbsp;<strong>18.03.2016&nbsp;</strong>statt, es wurde Jessica Vogt zum 3. Platz in Fahnenhochwurf geehrt, sie bekam die Goldmedaille.</p>
<p>Die Landesmeisterschaft im Fahnenhochwurf wurde am&nbsp;<strong>26.05.2016&nbsp;</strong>in Bretten abgehalten. Zum ersten Mal mit dabei war die zehnjährige Sitara Geisse, die in der Altersklasse auf Anhieb den zweiten Platz erreichte das ist die Silbermedaille. Lorena Karbstein machte den vierten Platz. Monika Günthner belegte den achten Platz.</p>
<p>Bei der Mannschaftswertung gewann Rottweil/Rastatt den dritten Platz.</p>
<p>Ein Ereignis war am&nbsp;<strong>25.06.2016&nbsp;</strong>die kirchliche Trauung von Judith und Daniel Flaig in der Kapellenkirche Rottweil. Die Fahnenschwinger standen beim Auszug aus der Kirche Spalier, für die musikalische Umrahmung sorgten Fanfaren mit Trommlern.&nbsp;</p>
<p>An der Eröffnungsfeier zur 54. Fußball-Bundesligasaision in der Münchner Allianz Arena, hatten die Fahnenschwinger aus Rottweil mit Freunden aus Bretten-Rastatt-Bad Urach-Niederburg Konstanz am&nbsp;<strong>26.08.2016</strong>&nbsp;ihren &nbsp;Auftritt. Die Fahne vom TSG 1899 Hoffenheim wurde von Lorena Karbstein geschwungen. Sie lieferten einen beeindruckenden Auftritt vor ca. 75000 Zuschauern.</p>
<p>Am&nbsp;<strong>10.09.2016</strong>&nbsp;hatten die Rottweiler Fahnenschwinger bereits den nächsten Termin, die 15. Weltmeisterschaft im Fahnenhochwurf. Lorena&nbsp; Karbstein belegte den 2. Platz, Jessica Vogt erreichte den 5. Platz. Für die Mannschaftwertung holte sich das Team Monika Günthner, Lorena Karbstein und Jessica Vogt den 1. Platz.</p>
<p>Den Landesfestumzug der Heimattage am&nbsp;<strong>11.09.2016&nbsp;</strong>in Bad Mergentheim, führten Monika Günthner und Jessica Vogt mit den Städtefahnen Rottweil-Ulm an. Lorena Karbstein mit der Gruppe des Landesverbands der Fahnenschwinger Baden-Württemberg e.V.</p>
<p>Der Vereinsausflug&nbsp; am&nbsp;<strong>01.10.2016&nbsp;</strong>führte nach Sigmaringen, mit&nbsp; Besichtigung des Schlosses und anschließendem Mittagsessen. Danach Zeit zur freien Gestaltung.</p>
<p>Die letzte Veranstaltung für dieses Jahr war der Rottweiler Weihnachtsmarkt. Dort hatten wir am&nbsp;<strong>10. und 11.12.2016</strong>&nbsp;einen Stand in der oberen Hauptstrasse. Es gab Glühwein, Kinderpunsch und Waffeln, aber der Renner war wie immer unsere Bretle.</p>