<h2 class="mb-5">Chronik aus dem Jahr 2017</h2>

<p>Am Sonntag den&nbsp;<strong>08.01.2017&nbsp;</strong>fand das Neujahrs – Kegeln in der Arche in Zimmern ob Rottweil statt.</p>
<p>Die Sportlerehrung der Stadt Rottweil fand am&nbsp;<strong>17.03.2017&nbsp;</strong>in der Stadthalle statt. Sitara Geisse belegte Platz 2 bei den Süddeutschen – Meisterschaften im Fahnenhochwurf mit 4,40 Meter, dafür bekam sie die Gold Medaille. Jessica Vogt, Monika Günthner und Lorena Karbstein belegten den 1. Platz in der Gruppe bei der Weltmeisterschaft im&nbsp;Fahnenhochwurf in Mergentheim,&nbsp; Dafür gab es Gold.</p>
<p>Die Mitgliederversammlung des Landesverbands der Spielmanns- und Fanfarenzüge BW fand am&nbsp;<strong>22.04.2017&nbsp;</strong>in Nusplingen statt. Es waren vom Fanfarenzug Rottweil Klaus Günthner und Hans-Peter Bucher anwesend.&nbsp; &nbsp;&nbsp;</p>
<p>Die Mitgliederversammlung des Fanfarenzugs Rottweil 1978 e.V. wurde im Gasthaus Hochbrücke am&nbsp;<strong>23.04.2017&nbsp;</strong>abgehalten.</p>
<p>Bei den Wahlen wurden sämtliche Amtsinhaber in ihren Ämtern bestätigt und neu gewählt.</p>
<p>Vorsitzender und Musikalischer Leiter wurde Klaus Günthner,</p>
<p>die Kassiererin Ute Thom sowie</p>
<p>Beisitzer der Fahnenschwinger Monika Günthner und</p>
<p>1. Beirat Thomas Roland.</p>
<p>Die Vereinsehrungen in Bronze:</p><ul> 	<li>Timo Flaig</li> </ul><p><strong>Die Vereinsehrungen in Silber:</strong></p><ul> 	<li>Lorena Karbstein</li> 	<li>Melissa Karbstein</li> 	<li>Christa Hauptmann</li> 	<li>Daniel Flaig</li> </ul><p><strong>Landesverband der Fahnenschwinger</strong><br> Abzeichen in Bronze:</p><ul> 	<li>Jessica Vogt</li> </ul><p><strong>Abzeichen in Silber:</strong></p><ul> 	<li>Ute Thom</li> 	<li>Monika Günthner</li> 	<li>Georg Abele</li> </ul><p>Mit kleiner Besetzung traten die Rottweiler Fahnenschwingerinnen bei den Deutschen Meisterschaften vom&nbsp;<strong>01.09. bis 03.09.2017&nbsp;</strong>in Bad Urach an. Im Damen Einzeln hatte Ute Thom den 10. Platz, Jessica Vogt den 12. Platz und Monika Günthner den 13. Platz belegt. Bei der Mannschaftswertung erreichten sie den 3. Platz und nehmen den&nbsp;Pokal für den 3. Platz in Empfang.</p>
<p>Der Regen hatte ein Einsehen, als der Fanfarenzug am&nbsp;<strong>09.09.2017&nbsp;</strong>an der Eröffnung des Stadtfestes mitwirkte. Die Fahnenschwingerinnen begeisterten die Zuschauer mit ihren Schwüngen und Würfen zu den Klängen der Landsknechtstrommeln.</p>
<p>Viel Zeit zum Feiern blieb ihnen jedoch nicht, da gleich am Sonntag&nbsp;<strong>10.09.2017&nbsp;</strong>&nbsp;der Landesfestumzug der Heimattage in Karlsruhe auf dem Programm stand. Monika Günthner, Jessica Vogt und Lorena Karbstein führten den Umzug mit Städtefahnen der vergangenen Heimattageorte an, während Melissa Karbstein die Gruppe der Fahnenschwinger des Landesverbandes verstärkte.&nbsp;</p>
<p>Anlässlich der Eröffnung des Thyssen-Krupp Testturm in Rottweil am Wochenende&nbsp;<strong>07./08.10.2017&nbsp;</strong>spielten drei Fanfarenspieler vom Schwarzen Tor aus zwei kleine Musikstücke. Zum 1. Gang des Festmahles an der langen Tafel erklangen weit über der Stadt Fanfarentöne. Vor dem 2. Gang &nbsp;spielten die Musiker erneut vom Schwarzen Tor aus in Richtung Innenstadt.</p>
<p>Am Weihnachtsmarkt hatte dann der Fanfarenzug am&nbsp;<strong>16.12. und 17.12.2017&nbsp;</strong>eine Weihnachtshütte. Es gab Glühwein, Kinderpunsch und Waffeln, aber der Renner war wie immer unsere Bretle.</p>