<h2 class="mb-5">Chronik aus dem Jahr 2018</h2>

<p>In das neue Jahr startete der Fanfarenzug Rottweil mit dem Kegeln welches&nbsp;am <strong>07.01.2018</strong> in der Arche in Zimmern mit guter Teilnahme statt fand.</p>
<p>Die Sportlerehrung der Stadt Rottweil war am <strong>16.03.2018</strong> in der Stadthalle. Die Fahnenschwinger des&nbsp;Fanfarenzug Rottweil 1978 e.V.&nbsp; belegten den 3. Platz in der Mannschaft&nbsp; anlässlich der 19. Deutschen Meisterschaft in Bad Urach. Die Mannschaft bestand aus Jessika Vogt, Monika Günthner und Ute Thom.&nbsp; Dafür bekamen sie die Ehrung in Gold.</p>
<p>Die Mitgliederversammlung des Fanfarenzug Rottweil 1978 e. V. wurde im Gasthaus Hochbrücke am <strong>17.03.2018</strong> abgehalten. Bei den Wahlen wurden sämtliche Amtsinhaber in ihren Ämtern bestätigt.&nbsp; Gewählt &nbsp;wurde der stellvertretende Vorsitzende <strong>Hans-Peter Bucher</strong>, Schriftführer <strong>Thomas Wiedeman</strong>n sowie die Pressewartin&nbsp; <strong>Anette Karbstein</strong> und als 2. Beirat <strong>Daniel Enzmann</strong>.</p>
<p><strong>Die Vereinsehrung in Bronze:</strong></p><ul> 	<li>Sitara Geisse</li> </ul><p><strong>&nbsp;Die Vereinsehrung in Silber:</strong></p><ul> 	<li>Annette Karbstein</li> 	<li>Andre Lengfeld</li> </ul><p><strong>Die Vereinsehrung in Gold:</strong></p><ul> 	<li>Thomas Schröter</li> </ul><p><strong>Die Vereinsehrung in Gold mit Kranz( 40 Jahre):</strong></p><ul> 	<li>Klaus Günthner</li> </ul><p>Der Fanfarenzug Rottweil gratuliert&nbsp; zum 40. Jährigen Vereinsjubiläum und bedankt sich hiermit für die geleistete Arbeit in den ganzen Jahren.</p>
<p>Am <strong>14. April</strong> <strong>2018</strong> war die Mitgliederversammlung des Landesverband der Spielmanns-und Fanfarenzüge in Essingen.</p>
<p>Ein &nbsp;weiteres Ereignis fand am <strong>25. Mai 2018 </strong>statt. Die Standesamtliche Trauung von unserem Kassenprüfer <strong>Tobias Bucher</strong> und seiner Frau Jenny im alten Rathaus zu Rottweil. Die Fahnenschwinger standen beim Auszug des Brautpaares aus dem Rathaus Spalier und die Fanfaren samt Trommler spielten unter der Leitung vom Daniel Flaig auf.</p>
<p>Am Samstag den <strong>09. Juni</strong> <strong>2018</strong> fand die 17.&nbsp; Weltmeisterschaft im&nbsp; Fahnenhochwurf in Nusplingen statt. An der Veranstaltung nahmen 68 Starter aus 12 Vereinen und 12 Mannschaften teil. In der Altersklasse Mädchen AK III (2005-2006) startete vom Fanfarenzug Rottweil 1978 e.V. <strong>Sitara Geisse.</strong> Sie überwarf in&nbsp; <strong>7,00</strong> <strong>m</strong> ein Hindernis und wurde in der Gesamtwertung <strong>&nbsp;Weltmeister. </strong></p>
<p>Am Sonntag&nbsp; den<strong> 24</strong>.<strong> Juni</strong> <strong>2018</strong> war in der Stadthalle Rottweil Tag des Sports.&nbsp; Da stellten sich die Vereine dem Publikum&nbsp; aus dem Umkreis vor, so auch der Fanfarenzug&nbsp; Rottweil 1978 e.V. mit Fanfare,&nbsp; Landsknechtstrommeln&nbsp; und Fahnen der Fahnenschwinger. Dabei waren Thomas Wiedemann,&nbsp;Monika Günthner,&nbsp;Hans-Peter Bucher und die Weltmeisterin Sitara Geisse.</p>
<p>Im Jubiläumsjahr 2018 wurde der Fanfarenzug Rottweil 1978 e. V. 40 Jahre alt. Die Feier dazu in der Domäne Hechingen am <strong>06. Juli 2018 </strong>bei einem Rittermahl des König Arthur mit Landsknechten, Rittern und Edeldamen, hat uns in eine Epoche entführt, in der man noch richtig zu feiern verstand. Die Kulisse und die mittelalterliche Atmosphäre waren ein Spektakel der ganz besonderen Art.</p>
<p>Am <strong>15. September 2018 </strong>präsentierten wir den Fanfarenzug Rottweil 1978 e. V. auf dem Wochenmarkt der Rottweiler Bevölkerung vor dem Apostelbrunnen in der Oberen Hauptstrasse.</p>
<p>Zum Abschluss des Vereinsjahres des Fanfarenzug Rottweil 1978 e.V. fand am <strong>09.12.2018</strong> ein Kegelnachmittag in der Arche Zimmern o. R. statt. Anschließend kehrten wir im Gasthaus Rößle ein und ließen das sportliche Jahr 2018 ausklingen.</p>
<p>Beim Weihnachtsmarkt in Rottweil hatte der Fanfarenzug am <strong>15.12.2018 </strong>wieder eine Weihnachtshütte. Es gab Glühwein, Kinderpunsch und Waffeln, aber der Renner waren wie immer unsere Bretle.</p>