<h2 class="mb-5">Chronik aus dem Jahr 2019</h2>

<p>Die Sportlerehrung der Stadt Rottweil war am <strong>15.03.2019</strong> in der Stadthalle.<br> Ehrungen in Gold erhielt unsere Weltmeisterin im Fahnenhochwurf Sitara Geisse.<br> Die Mannschaft aus Jessika Vogt, Monika Günthner und Ute Thom&nbsp;belegten den 3. Platz bei der Weltmiesterschaft. Dafür bekamen sie die Ehrungen in Gold.</p>
<p>Die Mitgliederversammlung des Fanfarenzug Rottweil 1978 e. V. wurde im Gasthaus Hochbrücke am <strong>18. Mai 2019</strong> abgehalten. Bei den Wahlen wurden sämtliche Amtsinhaber in ihren Ämtern bestätigt.&nbsp;</p>
<p>Gewählt &nbsp;wurde der Vorsitzende <strong>Klaus Günthner</strong>, Kassier<strong> Ute Thom,</strong> sowie die Beisitzer Fahnenschwinger <strong>Monika Günthner</strong> und als 1. Beirat <strong>Birgit Bucher </strong>sowie musikalischer Leiter <strong>Klaus Günthner.</strong></p>
<p><strong>Die Vereinsehrung in Bronze:</strong></p><ul> 	<li>Daniel Enzmann</li> </ul><p><strong>&nbsp;Die Vereinsehrung in Silber:</strong></p><ul> 	<li>Jasmin Diez</li> 	<li>Jessica Vogt</li> </ul><p>Traditionell&nbsp; am&nbsp; letzten Sommerferienwochenende feiert die Stadt Rottweil gemeinsam mit Rottweiler Bürgern und vielen Vereinen im zweijährigen Turnus&nbsp;das Rottweiler Stadtfest am&nbsp;<strong>07. September 2019</strong> unter dem Thema: 500 Jahre Ewiger Bund.</p>
<p>Am Samstag den <strong>21. September 2019 </strong>fand die Weltmeisterschaft im Fahnenhochwurf in Eschweiler statt. An der Veranstaltung nahmen vom den Fahnenschwinger <strong>Monika Günthner,&nbsp; Jessica Vogt, Lorena Karbstein</strong> teil. Sie belegten den&nbsp; 2. Platz in der Mannschaftswertung.</p>
<p>Der Jahresausflug führte uns nach Alpirsbach. Nach der Ankunft gab es im Brauereigasthof Löwen – Post das Mittagessen, danach fand die Stadtführung unter dem Motto <strong>„Heiler, Hexen, Kräuterweiber“</strong> statt. Bei der Führung im Kloster Alpirsbach sahen wir Historische Orgel-Skulpturen und „<strong>Mönche und Scholaren“.</strong><br> Zum Abschluss des Vereinsausflugs trafen wir uns im Kaffee am Kloster. Danach gings auf die Heimreise.</p>
<p>Die Bezirksversammlung Süd fand am <strong>26. Oktober 2019 </strong>in Schwenningen statt.</p>
<p>Unter dem Motto: <strong>Ein Herz für den Rottweiler – Hund </strong>trafen sich Halter von Rottweiler Hunden aus ganz Deutschland und den Nachbarländern Schweiz und Frankreich in der ältesten Stadt Baden–Württembergs. Höhepunkt war der Demonstrationszug durch die Obere Hauptstraße. Angeführt von den Fahnenschwingern und der Trommelgruppe des Fanfarenzugs&nbsp; Rottweil 1978 e.V.&nbsp;<br> Beim Rathaus spielten wir gemeinsam mit den Fahnenschwingern auf.</p>
<p>Zum Abschluss des Vereinsjahres des Fanfarenzug Rottweil 1978 e.V. fand am&nbsp;<strong>08. Dezember 2019</strong> ein Kegelnachmittag in der Arche Zimmern o. R. statt.<br> Anschließend kehrten wir im Gasthaus zur Kanne ein und ließen das sportliche Jahr 2019 mit einem Essen ausklingen.</p>
<p>Beim Weihnachtsmarkt in Rottweil hatte der Fanfarenzug am <strong>15. Dezember 2019&nbsp;</strong>wieder eine Weihnachtshütte.</p>