<h2 class="mb-5">Geschichte der Fanfaren</h2>

<p>Die Geschichte der Fanfare (Naturtrompete) lässt sich bis in das 4. Jahrtausend vor Christus zurückverfolgen. Bei den ersten&nbsp; „Trompeten“ handelte es sich dabei um gerade Holz-, oder Bambus- Röhren ohne Mundstück und Trichter. Sie wurden wegen ihres weithin vernehmbaren Schalles als Signalinstrumente im zivilen, im militärischen und im religiösen Bereich eingesetzt. Im Krieg wurden mit ihrer Hilfe Kommandos übermittelt, die Kämpfer angefeuert und die Gegner in Furcht und Schrecken versetzt. Vielerorts galt die Trompete als heiliges Instrument. So soll zum Beispiel die ägyptische Trompete<i>, </i>welche etwa um 1400 v.Chr. geblasen wurde, von Gott Osiris erfunden worden sein. Auch bei den Assyrern und bei den Israeliten war die Trompete bekannt. Die israelitische Trompete war aus Silber und hieß <i>„Chazozra“</i>.
</p>
<p>Auf diesen Instrumenten wurde keine Musik nach unserer heute bekannten Art gespielt, denn man heulte, sang, murmelte oder prustete in die obere Rohröffnung, wobei „unheimliche Töne“ entstanden, die als eselsschreiend, roh, rauh, und schreckenerregend beschrieben wurden.
</p>
<p>Bei den alten Griechen hieß die Trompete <i>„Salpinx“</i>. Trompetenblasen soll auch eine Disziplin bei den Pythischen Spielen von Delphi (Musik- und Gesangswettbewerbe), die zu Ehren des Gottes Apollo durchgeführt wurden, gewesen sein (Sportwettbewerbe zu Ehren des Zeus wurden in Olympia durchgeführt). Die Römer verwendeten die langgestreckte <i>„Tuba“</i> und das gebogene, hornähnliche <i>„Cornu“</i> als Signalinstrumente in ihren Legionen und bei Gladiatorenkämpfen. Die Tuba wurde auch bei einem im April stattfindenden Trompeterfest geblasen. Ein weiteres römisches Instrument war der hakenförmige „<i>Lituus“</i>. Aus der Bronzezeit sind die Instrumente der Germanen, die <i>„Luren",</i> bekannt. Diese S-förmigen Instrumente aus Bronze-Guss waren durchweg konisch gefertigt, hatten keinen Schalltrichter, sondern einen Teller als Endstück und waren mit einem Mundstück versehen. Auch die Kelten hatten Trompeten, welche dem hakenförmigen, römischen Lituus ähnlich waren und <i>„Karnyx“</i> genannt wurden.
</p>
<p>Nach dem Fall des Weströmischen Reiches 476 n.Chr. wurde es in Europa still um die Trompete. Im Jahre 711 n.Chr. vielen die Araber, damals Sarazenen genannt, in Spanien ein. Als die Sarazenen 1073 n.Chr. Palestina eroberten brachen die europäischen Herrscher zu den Kreuzzügen auf um das „Heilige Land“ zu befreien. Man nimmt an, dass über die Sarazenen erstmals langgestreckte, aus geraden, dünnen Röhren gefertigte Instrumente mit enger Mensur und flachem Schallbecher nach Zentraleuropa gelangten. Sie wurden Businen genannt. Andere Historiker glauben, dass diese Instrumente in Süditalien entstanden sind.
</p>
<p>Wie auch immer, die Busine ist offenbar der direkte, etwas unhandliche Urahn der heutigen Blechtrompeten. Etwa um 1400 kam die Technik des Rohrbiegens auf und die langen, geraden Röhren der Busine wurden zunächst s-förmig, später in Schlaufenform gebogen. Diese Form hat sich bis heute erhalten.
</p>
<p>Seit dem 10. Jahrhundert wurde den europäischen Bauern nach und nach das Recht auf Waffenbesitz entrissen. Gleichzeitig sorgte das erstarkende Königtum, dass das Volksaufgebot duch ein Aufgebot an berittenen Vasallen ersetzt wurde. Allmählich entstanden die Ritterheere, welche bis weit in das 14. Jahrhundert hinein das Militärwesen bestimmten. Die Busine war das Lieblingsinstrument der Ritter. Bereits im 13. Jahrhundert wurden die Businen mit wappenverzierten Standartentüchern versehen. Etwa um 1400 kam die Technik des Rohrbiegens auf. Man füllte die Röhren dazu mit Blei, das nach dem Biegen wieder ausgeschmolzen wurde. Die Trompeten konnten seit dieser Zeit in einer handlicheren, der heute noch gültigen Schlaufen- (oder Bügel-) Form hergestellt werden. Waren um 1300 nur vier Töne spielbar, konnten um 1400 bereits sechs bis acht Töne erzeugt werden. Man spielte aber immer nur einzelne Töne. Der helle, strahlende Klang fand Gefallen bei den Mächtigen der Zeit und die Trompete wurde zum Instrument des Adels und der Freien Reichsstädte. 1416 wurden die Trompeter unter kaiserlichen Schutz gestellt. Im 16. Jahrhundert begann man Melodien zu spielen. Im 17. Jahrhundert wurden die Feldtrompeter den Offizieren gleich gestellt und durften wie diese Straußenfedern am Hut tragen.
</p>
<p>Das goldene Zeitalter der Naturtrompete war zwischen 1600 und 1750.&nbsp; Die großen Komponisten dieser Zeit, z.B. Bach und Haydn, begannen Stücke für die Trompete zu komponieren, wobei das e``` (das entspricht dem 20. Naturton) keine Seltenheit war. Per Kaiserlichem Edikt bildete sich 1623 die „Reichszunft der Heerpauker und Feldtrompeter“.
</p>
<p>Am Ende des 18. Jahrhunderts wurden an den Trompeten Klappen, Züge und Stimmbögen angebracht, damit der Tonumfang chromatisch erweitert werden konnte. Als um 1820 das Pumpventil und damit die Ventiltrompete entstand, wurde die Trompete voll melodiefähig. Damit begann der Niedergang der Naturtrompete.
</p>
<p>Fanfarenzüge verwenden Naturtrompeten, hier allerdings meist Fanfaren genannt, die noch immer den im 17. Jahrhundert gebauten Modellen sehr ähnlich sind. Die Instrumente sind heutzutage zum größten Teil in ES gestimmt.
</p>
<p>&nbsp;</p>
<p><i><sub>Quelle: 2016 /&nbsp;Klaus Günthner, Präsident des Landesverband der Spielmanns- und Fanfarenzüge Baden-Württemberg</sub></i>
</p>
<p>&nbsp;</p>